image:
  file: .gitpod.dockerfile
# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Script Task
    init: source init.sh # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
    command: echo "this script has started"

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
#No need to exports ports as this is not a webapp
#ports:
#  - name: Frontend
#    description: Port 3000 for the frontend
#    port: 3000
#    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
